before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_install:
  - gem install bundler

script:
  rake

rvm:
 - 1.9.3
 - 2.0.0

gemfile:
  - Gemfile

services:
  - memcache
