# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "memcached-manager"
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thiago Fernandes Massa"]
  s.date = "2013-10-27"
  s.description = "A sinatra memcached-manager that allows you to view status, flush/view keys and so on. Also easily pluggable to a Rails app."
  s.email = "thiagown@gmail.com"
  s.executables = ["memcached-manager"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "config.ru"
  ]
  s.homepage = "http://github.com/thiagofm/memcached-manager"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A sinatra memcached-manager that allows you to view status, flush/view keys and so on. Also easily pluggable to a Rails app."
  s.test_files = ["spec/javascripts", "spec/javascripts/angular", "spec/javascripts/angular/controllers", "spec/javascripts/angular/controllers/list_keys_controller_spec.js", "spec/javascripts/angular/services", "spec/javascripts/angular/services/notification_spec.js", "spec/javascripts/angular/services/resource_spec.js", "spec/javascripts/angular/services/response_spec.js", "spec/javascripts/helpers", "spec/javascripts/helpers/angular-mocks.js", "spec/javascripts/helpers/SpecHelper.js", "spec/javascripts/support", "spec/javascripts/support/jasmine.yml", "spec/javascripts/support/jasmine_helper.rb", "spec/lib", "spec/lib/extensions", "spec/lib/extensions/api_response_spec.rb", "spec/lib/extensions/error_spec.rb", "spec/lib/extensions/memcached_connection_spec.rb", "spec/lib/extensions/memcached_inspector_spec.rb", "spec/lib/extensions/memcached_settings_spec.rb", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_runtime_dependency(%q<dalli>, [">= 0"])
      s.add_runtime_dependency(%q<vegas>, [">= 0"])
      s.add_runtime_dependency(%q<thin>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_development_dependency(%q<jasmine>, ["= 1.3.2"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_dependency(%q<dalli>, [">= 0"])
      s.add_dependency(%q<vegas>, [">= 0"])
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_dependency(%q<jasmine>, ["= 1.3.2"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<sinatra-contrib>, [">= 0"])
    s.add_dependency(%q<dalli>, [">= 0"])
    s.add_dependency(%q<vegas>, [">= 0"])
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
    s.add_dependency(%q<jasmine>, ["= 1.3.2"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

